const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const iconsDir = path.join(root, 'node_modules', 'lucide-react-native', 'dist', 'esm', 'icons')
const IMPORT_RE = /import\s*\{([^}]+)\}\s*from\s*'lucide-react-native'/g

function sourceFiles(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      sourceFiles(full, out)
    } else if (/\.tsx?$/.test(entry.name)) {
      out.push(full)
    }
  }
  return out
}

/** Export name → icon file, read from the package's own index (aliases included). */
function iconFiles() {
  const index = fs.readFileSync(path.join(iconsDir, '..', 'lucide-react-native.mjs'), 'utf8')
  const files = new Map()
  for (const match of index.matchAll(/export \{([^}]+)\} from '\.\/icons\/([^']+)\.mjs'/g)) {
    for (const part of match[1].split(',')) {
      const name = part.trim().replace(/^default as /, '')
      files.set(name, match[2])
    }
  }
  return files
}

/**
 * Write a module that re-exports only the icons the app imports, each from
 * its own file. Metro has no tree shaking: importing the package's index
 * would bundle and evaluate all ~1,800 icons at startup. metro.config.js
 * points `lucide-react-native` at this file.
 */
function writeIconBarrel(target) {
  const icons = new Set()
  for (const file of [path.join(root, 'App.tsx'), ...sourceFiles(path.join(root, 'src'))]) {
    const text = fs.readFileSync(file, 'utf8')
    for (const match of text.matchAll(IMPORT_RE)) {
      for (const name of match[1].split(',')) {
        const icon = name.trim()
        if (icon && !icon.startsWith('type ')) {
          icons.add(icon.split(/\s+as\s+/)[0])
        }
      }
    }
  }
  const files = iconFiles()
  const lines = [...icons].sort().map((icon) => {
    const file = files.get(icon)
    if (!file) {
      throw new Error(`lucide-react-native has no icon named "${icon}"`)
    }
    return `export { default as ${icon} } from 'lucide-react-native/icons/${file}'`
  })
  const content = `// Generated by scripts/icon-barrel.js — do not edit.\n${lines.join('\n')}\n`
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) {
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, content)
  }
  return target
}

module.exports = { writeIconBarrel }
